# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/dumb_inputs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client/dumb_inputs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x63lient/dumb_inputs.proto\"R\n\x0bInputAction\x12!\n\tkeyEvents\x18\x01 \x03(\x0b\x32\x0e.KeyboardEvent\x12\x0f\n\x07mouseDx\x18\x02 \x01(\x11\x12\x0f\n\x07mouseDy\x18\x03 \x01(\x11\";\n\rKeyboardEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\teventType\x18\x02 \x01(\x0e\x32\n.EventType*#\n\tEventType\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01\x62\x06proto3')
)

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELEASE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=173,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
PRESS = 0
RELEASE = 1



_INPUTACTION = _descriptor.Descriptor(
  name='InputAction',
  full_name='InputAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyEvents', full_name='InputAction.keyEvents', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mouseDx', full_name='InputAction.mouseDx', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mouseDy', full_name='InputAction.mouseDy', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=110,
)


_KEYBOARDEVENT = _descriptor.Descriptor(
  name='KeyboardEvent',
  full_name='KeyboardEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeyboardEvent.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='KeyboardEvent.eventType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=171,
)

_INPUTACTION.fields_by_name['keyEvents'].message_type = _KEYBOARDEVENT
_KEYBOARDEVENT.fields_by_name['eventType'].enum_type = _EVENTTYPE
DESCRIPTOR.message_types_by_name['InputAction'] = _INPUTACTION
DESCRIPTOR.message_types_by_name['KeyboardEvent'] = _KEYBOARDEVENT
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputAction = _reflection.GeneratedProtocolMessageType('InputAction', (_message.Message,), dict(
  DESCRIPTOR = _INPUTACTION,
  __module__ = 'client.dumb_inputs_pb2'
  # @@protoc_insertion_point(class_scope:InputAction)
  ))
_sym_db.RegisterMessage(InputAction)

KeyboardEvent = _reflection.GeneratedProtocolMessageType('KeyboardEvent', (_message.Message,), dict(
  DESCRIPTOR = _KEYBOARDEVENT,
  __module__ = 'client.dumb_inputs_pb2'
  # @@protoc_insertion_point(class_scope:KeyboardEvent)
  ))
_sym_db.RegisterMessage(KeyboardEvent)


# @@protoc_insertion_point(module_scope)
